# Generated by Django 3.1.1 on 2020-09-25 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PARENT_BRAND', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRAND_NAME', models.CharField(max_length=30)),
                ('SHAREHOLDER', models.BooleanField(default=False)),
                ('SUBSIDIARY', models.BooleanField(default=False)),
                ('SUB_BRAND', models.BooleanField(default=False)),
                ('PARENT_BRAND', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='nestle.parent')),
            ],
        ),
    ]
